-- Schéma Pulse (pulse-reactive, R2DBC). Joué par spring.sql.init au démarrage et
-- contre la base éphémère Testcontainers en test. Idempotent (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS alert (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(120)     NOT NULL,
    threshold   DOUBLE PRECISION NOT NULL,
    severity    VARCHAR(16)      NOT NULL,
    created_at  TIMESTAMPTZ      NOT NULL
);

-- Trace d'audit écrite dans la MÊME transaction que l'alerte (Partie C).
-- `target` (qui reçoit le metric_name) est volontairement plus étroite que
-- alert.metric_name (VARCHAR(64) vs VARCHAR(120)) : c'est le levier qui permet, en test,
-- de forcer l'échec de l'insert d'audit (metric_name long accepté par `alert` mais trop
-- long pour `target`) et donc de prouver le rollback de l'alerte — sans rien mocker.
CREATE TABLE IF NOT EXISTS audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id  BIGINT      NOT NULL,
    action    VARCHAR(16) NOT NULL,
    target    VARCHAR(64) NOT NULL,
    logged_at TIMESTAMPTZ NOT NULL
);
